import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillYoutube,
  AiFillInstagram,
  AiFillGoogleCircle,
  AiFillGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/me.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/basketball.png";
import Image from "next/image";
import web1 from "../public/codes.jpeg";
import web2 from "../public/melo.gif";
import web3 from "../public/curb.webp";
import web4 from "../public/diaryofamadman.webp";
import web5 from "../public/balls.gif";
import web6 from "../public/sun.webp";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Texas & Florida</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
              <a
  className="bg-gradient-to-r from-blue-500 to-orange-500 text-white px-4 py-2 border-none rounded-md ml-8"
  href="/JAResume2023.pdf"
  download="JAResume2023.pdf"
>
  Resume Download
</a>

              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-orange-600 font-medium dark:text-orange-400 md:text-6xl">
              Justin Adam
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Computer Science
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Student at the University of Florida pursuing a degree in computer science in the Weirthem College of Engineering.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/justin22a">
              <AiFillGithub />
           </a>
           <a href="https://www.linkedin.com/in/justin-adam-a566a11ab">
             <AiFillLinkedin />
           </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-orange-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">What I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my college years I have studied the <span className="text-orange-500"> theoretical </span> and <span className="text-orange-500"> practical </span> side of computer science. I have redeveloped games from scratch, recreated parts of an operating system, and built a few practical projects like a stock screener that uses an api. 
              I hope to apply these technical skills to benefit a working environment.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              On a <span className="text-orange-500"> team </span> I strive to help those around me, lead when necessary, get along with anyone, invest time in strategic planning,
              and absorb new information like a sponge.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Career Goals       
                       </h3>
              <p className="py-2">
                Start out learning the technical background like software engineering, 
               then become a leader within a company with proper experience.
              </p>
              <h4 className="py-4 text-orange-600">Steps to Acheive Goals</h4>
              <p className="text-gray-800 py-1">Finish undergrad</p>
              <p className="text-gray-800 py-1">Full time work experience</p>
              <p className="text-gray-800 py-1">Get an MBA</p>
              <p className="text-gray-800 py-1">Polish Soft/Technical Skills</p>
              <p className="text-gray-800 py-1">Make awesome friends/relationships</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Technical Skills
              </h3>
              <p className="py-2">
                Languages: C++, HTML, Python, C, Java, JavaScript, Assembly
              </p>
              <p className="py-2">
                Software: React, Linux, Git, VS Code, JetBrains
              </p>
              <h4 className="py-4 text-orange-600">Projects</h4>
              <p className="text-gray-800 py-1">Portfolio site</p>
              <p className="text-gray-800 py-1">Linux: Memory manager & Wad File System</p>
              <p className="text-gray-800 py-1">Discord Bot - alerts for internship opportunities (IP)</p>
              <p className="text-gray-800 py-1">BeStrong App - Gym Community App (IP)</p>
              <p className="text-gray-800 py-1">Minesweeper - Game</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Fun Facts: Who Am I?</h3>
              <p className="py-2">
                Born in northern New Jersey, then moved to Texas for most of childhood. Ended up in Florida for college.
              </p>
              <h4 className="py-4 text-orange-600">Facts</h4>
              <p className="text-gray-800 py-1">Huge NY Knicks Fan</p>
              <p className="text-gray-800 py-1">Love playing basketball</p>
              <p className="text-gray-800 py-1">Easily sunburned</p>
              <p className="text-gray-800 py-1">Used to cheerlead</p>
              <p className="text-gray-800 py-1">Have an australian kelpie and pug back home</p>
              <p className="text-gray-800 py-1">Favorite Movie: Anchorman</p>
              <p className="text-gray-800 py-1">Favorite Show: Curb Your Enthusiasm</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Images that describe me</h3>
            
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              
              <span className="text-teal-500">  </span>
           <span className="text-teal-500"> </span>
             
             
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
